### ISSUE TITLE
CI: Coverage workflow failing - TauriService.setSelectedModel mock missing

### ISSUE THREAD

**Issue by mmogr** [mmogr/gglib#33]
## Problem
The Coverage CI workflow is failing on `main` after merging PR #31 (macOS menu bar feature).

## Error
```
TypeError: TauriService.setSelectedModel is not a function
  ❯ Object.selectModel src/hooks/useModels.ts:33:18
```

5 test cases in `tests/ts/hooks/useModels.test.ts` are failing.

## Root Cause
PR #31 added `setSelectedModel` method to `TauriService` and updated the `useModels` hook to call it, but the test mock was not updated to include this new method.

## Affected Files
- `tests/ts/hooks/useModels.test.ts` - mock is missing `setSelectedModel`
- `src/hooks/useModels.ts:33` - calls the new method

## Fix
Add `setSelectedModel: vi.fn().mockResolvedValue(undefined)` to the TauriService mock.
