### ISSUE TITLE
fix(runtime): Windows release CI fails with E0603 — module `gpu` is private

### ISSUE THREAD

**Issue by mmogr** [mmogr/gglib#351]
## Bug

Both the `Build x86_64-pc-windows-msvc` and `Build GUI x86_64-pc-windows-msvc` jobs in the release CI have been failing since #348 with:

```
error[E0603]: module `gpu` is private
   --> crates\gglib-runtime\src\llama\download\mod.rs:158:38
    |
158 |             let gpu = crate::system::gpu::detect_gpu_info();
    |                                      ^^^  --------------- function `detect_gpu_info` is not publicly re-exported
```

Full failed run: https://github.com/mmogr/gglib/actions/runs/23010217585

## Root cause

Commit #348 (`f9870eb`) added a Windows-only code path in `crates/gglib-runtime/src/llama/download/mod.rs` that accesses `crate::system::gpu::detect_gpu_info()` by absolute path. However, `gpu` is declared as a private `mod gpu;` inside `system/mod.rs`:

```rust
// system/mod.rs — before fix
mod commands;
mod deps;
mod gpu;   // ← private, not accessible via crate::system::gpu::
```

Because the offending code is inside `#[cfg(target_os = "windows")]`, the error is invisible on macOS/Linux CI and only surfaces on the Windows runner.

## Fix

Change `mod gpu;` to `pub(crate) mod gpu;` in `crates/gglib-runtime/src/system/mod.rs`. This makes the module accessible anywhere in the `gglib-runtime` crate without leaking it as public API (even though `system` itself is `pub mod` in `lib.rs`).
